name = "worker-d1"
main = "src/index.ts"
compatibility_date = "2023-11-21"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "northwind-demo"
database_id = "30c8d1a8-0cfb-4d6b-87f0-32ddbaa67b68" # Replace with your ID from `wrangler d1 create`
